name: psy_therapist
description: Psy - Seu Terapeuta Virtual focado em saúde mental
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  
  # Utils
  uuid: ^4.1.0
  intl: ^0.19.0
  
  # Firebase
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_auth: ^5.6.2
  cloud_functions: ^5.0.1
  firebase_app_check: ^0.3.0
  firebase_analytics: ^11.5.1

  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
